---
# tasks file for server-role
- name: Disable Selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  #notify: reboot selinux

- name: Rebooting SELinux
  meta: flush_handlers

- name: Install Zabbix Repos
  dnf:
    name: "https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm"
    disable_gpg_check: True
    state: present

- name: install zabbix web packages
  dnf:
    name: "{{packages}}"
    state: present

- name: Install PHPFM repos
  dnf:
    name: "http://rpms.remirepo.net/enterprise/remi-release-8.rpm"
    disable_gpg_check: True
    state: present

- name: Enable the PHPFM repos
  dnf:
    name: "@php:remi-7.4"
    state: present

- name: Installing PHP packages
  dnf:
    name: "{{php_packages}}"
    state: present

- name: Starting the Php-fpm service
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    #- httpd
    - php-fpm

- name: open http service
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled


- name: configure zabbix front end 
  template:
    src: templates/zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php

- name: create resource for apache Enable the server-status page
  template:
    src: templates/serverstatus.conf.j2 
    dest: /etc/httpd/conf.d/serverstatus.conf

- name: Configure Apache to listen on VIP of the front end cluster
  shell: echo "Listen 192.168.56.22" > /etc/httpd/conf/httpd.conf
  changed_when: false


-  name: pcs defualt resouces setting 
   shell: pcs resource defaults update resource−stickiness=100 --force
   when: inventory_hostname == 'zabbix_web01'
   changed_when: false


- name: start Zabbix server daemon on HA cluster 
  shell: pcs resource create zabbix_http_web  ocf:heartbeat:apache configfile=/etc/httpd/conf/httpd.conf  statusurl="http://localhost:8080/server−status" --group zabbix_web_cluster --force
  when: inventory_hostname == 'zabbix_web01'
  changed_when: false 

