---
- name: install db packages
  dnf:
    name: "{{packages}}"
    state: present

- name: start and enable db services
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    "{{services}}"

- name: create root password
  mysql_user:
    name: root
    host: localhost
    password: "{{ root_db_password }}"

- name: copy .my.cnf file with root password credentials
  template:
    src: templates/.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: '0600'

- name: create file /etc/my.cnf.d/zabbixdb.cnf
  file:
    path: /etc/my.cnf.d/zabbixdb.cnf
    state: touch
  notify: import zabbix schema
 
- name: copy file config 
  template:
    src: templates/.my.cnf.j2
    dest: /etc/my.cnf.d/zabbixdb.cnf

- name: update mysql root password login for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ root_db_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: create  zabbix user 
  mysql_db: 
    name: zabbix
    collation: utf8_bin
    encoding: utf8
    state: present
  notify: import zabbix schema

- name: Meta Zabbix db
  meta: flush_handlers
 

- name: grant  zabbix db user all privilleges
  mysql_user:
    name: "{{zabbix_db_user}}"
    password: "{{zabbix_db_password}}"
    priv: 'zabbix.*:ALL'
    host: localhost
    state: present
