---
- name: Disable Selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  #notify: reboot selinux

- name: Rebooting SELinux
  meta: flush_handlers

- name: Install Zabbix Repos
  dnf:
    name: "https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm"
    disable_gpg_check: True
    state: present

- name: install db packages
  dnf:
    name: "{{packages}}"
    state: present

- name: start and enable db services
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    "{{services}}"

- name: open port 3306
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: update mariadb password
  mysql_user:
    name: root
   # login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{root_db_password}}"
    priv: "*.*:ALL,GRANT"
    state: present
    login_password: "{{ root_db_password }}"
   # host: "{{item}}"
   # check_implicit_admin: true
  #loop:
   # - localhost

- name: update my.cnf config
  template:
    src: templates/my.cnf.j2   
    dest: /etc/my.cnf
    mode: 0600
    owner: root

- name: grant privileges to root user
  mysql_user:
    name: root
    host: "{{item}}"
    password: "{{ root_db_password }}"
    login_password: "{{ root_db_password }}"
  with_items:
    - 127.0.0.1
    - ::1    
    - localhost

- name: create file /etc/my.cnf.d/zabbixdb.cnf
  file:
    path: /etc/my.cnf.d/zabbixdb.cnf
    state: touch
  changed_when: false
  notify: import zabbix schema
 
- name: copy file config 
  template:
    src: templates/zabbixdb.cnf.j2
    dest: /etc/my.cnf.d/zabbixdb.cnf


    
- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    host: localhost
    password: "{{ root_db_password }}"
    login_password: "{{ root_db_password }}"

- name: create  zabbix user 
  mysql_db: 
    name: zabbix
    login_password: "{{ root_db_password }}"
    login_user: root
    collation: utf8_bin
    encoding: utf8
    state: present
  notify: import zabbix schema

- name: Meta Zabbix db
  meta: flush_handlers
 

- name: grant  zabbix db user all privilleges
  mysql_user:
    name: "{{zabbix_db_user}}"
    login_password: "{{ root_db_password }}"
    login_user: root
    password: "{{zabbix_db_password}}"
    priv: 'zabbix.*:ALL'
    host: localhost
    state: present

