---
# tasks file for server-role
- name: Disable Selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  #notify: reboot selinux

- name: Rebooting SELinux
  meta: flush_handlers

- name: Install Zabbix Repos
  dnf:
    name: "https://repo.zabbix.com/zabbix/5.2/rhel/8/x86_64/zabbix-release-5.2-1.el8.noarch.rpm"
    disable_gpg_check: True
    state: present

- name: install zabbix server-role
  dnf:
    name: zabbix-server
    state: present

- name: configure server file /etc/zabbix/zabbix_server.conf
  template:
     src: templates/zabbix_server.conf.j2
     dest: /etc/zabbix/zabbix_server.conf

-  name: pcs defualt resouces setting 
   shell: pcs resource defaults update resource−stickiness=100 --force
   when: inventory_hostname == 'zabbix_server01'
   changed_when: false


- name: start Zabbix server daemon on HA cluster 
  shell: pcs resource create cluster_zabbix_deamon service:zabbix-server --group zabbix_svr_cluster --force
  when: inventory_hostname == 'zabbix_server01'
  changed_when: false
  failed_when: false

- name: add pcs resource colocation
  shell: pcs constraint colocation add ClusterIP  with cluster_zabbix_deamon score=INFINITY --force
  when: inventory_hostname == 'zabbix_server01'
  changed_when: false

- name: configure pcs constrain
  shell: pcs constraint order ClusterIP then cluster_zabbix_deamon
  when: inventory_hostname == 'zabbix_server01'
  changed_when: false

    
- name: add pcs Zabbix Server start interval
  shell: pcs resource update cluster_zabbix_deamon op start interval=0s timeout=60s
  when: inventory_hostname == 'zabbix_server01'
  changed_when: false

- name: add pcs ZabbixServer stop interval
  shell: pcs resource update cluster_zabbix_deamon op stop interval=0s timeout=120s
  when: inventory_hostname == 'zabbix_server01'
  changed_when: false